CREATE TABLE USUARIO (
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(255) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    FUNCAO VARCHAR2(255) NOT NULL
);

CREATE TABLE TAREFA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(1000),
    STATUS VARCHAR(50),
    DATA_INICIO TIMESTAMP,
    DATA_FIM TIMESTAMP,
    ID_USUARIO BIGINT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);